POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/ce9cd6fe-f2ae-482a-848c-5e6d4ead81fa/attendees
Content-Type: application/json

{
  "name": "Raphael Costa",
  "email": "rafa.costa2@hotmail.com"
}