POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/8f763e80-ec2d-43d0-8685-af4687418a24/attendees
Content-Type: application/json

{
  "name": "Raphael Costa",
  "email": "rafa.costa1@hotmail.com"
}

###

GET http://localhost:3333/events/8f763e80-ec2d-43d0-8685-af4687418a24

